spring:
  application:
    name: ExpenseTrackingAPI

  profiles:
    active: dev

  # Flyway for migrations
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    validate-on-migrate: true

  # Database config
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_dev
    username: postgres
    password: fw18_0433
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.expensetracker: DEBUG
    org.flywaydb: DEBUG
    org.flywaydb.core: DEBUG     # ‚Üê Yeh add kar (core package)
    org.flywaydb.core.internal: DEBUG